f = open(r'm2l1\text.txt', 'w', encoding='utf-8')
text = 'THE GREATEST TÜRKİYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE'
f.write(text)
f.close()
